// ── Bengali display names for the app's district values ──
// Keyed by the exact English strings used as district values everywhere
// (ZoneSelect / DELIVERY_ZONES / checkout / admin / orders). Values stay
// English in storage — this map is display-only.
// Includes the two zone groupings ('Dhaka City', 'Dhaka Suburban') and the
// Dhaka-district upazillas surfaced as standalone options (Savar, Dhamrai,
// Keraniganj).
export const DISTRICT_NAMES_BN: Record<string, string> = {
  'Dhaka City': 'ঢাকা সিটি',
  'Dhaka Suburban': 'ঢাকা সাবআরবান',
  'Savar': 'সাভার',
  'Dhamrai': 'ধামরাই',
  'Keraniganj': 'কেরানীগঞ্জ',
  'Bagerhat': 'বাগেরহাট',
  'Bandarban': 'বান্দরবান',
  'Barguna': 'বরগুনা',
  'Barishal': 'বরিশাল',
  'Bhola': 'ভোলা',
  'Bogura': 'বগুড়া',
  'Brahmanbaria': 'ব্রাহ্মণবাড়িয়া',
  'Chandpur': 'চাঁদপুর',
  'Chattogram': 'চট্টগ্রাম',
  'Chapainawabganj': 'চাঁপাইনবাবগঞ্জ',
  'Chuadanga': 'চুয়াডাঙ্গা',
  'Cox’s Bazar': 'কক্সবাজার',
  'Cumilla': 'কুমিল্লা',
  'Dinajpur': 'দিনাজপুর',
  'Faridpur': 'ফরিদপুর',
  'Feni': 'ফেনী',
  'Gaibandha': 'গাইবান্ধা',
  'Gazipur': 'গাজীপুর',
  'Gopalganj': 'গোপালগঞ্জ',
  'Habiganj': 'হবিগঞ্জ',
  'Jamalpur': 'জামালপুর',
  'Jashore': 'যশোর',
  'Jhalokathi': 'ঝালকাঠি',
  'Jhenaidah': 'ঝিনাইদহ',
  'Joypurhat': 'জয়পুরহাট',
  'Khagrachhari': 'খাগড়াছড়ি',
  'Khulna': 'খুলনা',
  'Kishoreganj': 'কিশোরগঞ্জ',
  'Kurigram': 'কুড়িগ্রাম',
  'Kushtia': 'কুষ্টিয়া',
  'Lakshmipur': 'লক্ষ্মীপুর',
  'Lalmonirhat': 'লালমনিরহাট',
  'Madaripur': 'মাদারীপুর',
  'Magura': 'মাগুরা',
  'Manikganj': 'মানিকগঞ্জ',
  'Meherpur': 'মেহেরপুর',
  'Moulvibazar': 'মৌলভীবাজার',
  'Munshiganj': 'মুন্সিগঞ্জ',
  'Mymensingh': 'ময়মনসিংহ',
  'Naogaon': 'নওগাঁ',
  'Narail': 'নড়াইল',
  'Narayanganj': 'নারায়ণগঞ্জ',
  'Narsingdi': 'নরসিংদী',
  'Natore': 'নাটোর',
  'Netrokona': 'নেত্রকোণা',
  'Nilphamari': 'নীলফামারী',
  'Noakhali': 'নোয়াখালী',
  'Pabna': 'পাবনা',
  'Panchagarh': 'পঞ্চগড়',
  'Patuakhali': 'পটুয়াখালী',
  'Pirojpur': 'পিরোজপুর',
  'Rajbari': 'রাজবাড়ী',
  'Rajshahi': 'রাজশাহী',
  'Rangamati': 'রাঙামাটি',
  'Rangpur': 'রংপুর',
  'Satkhira': 'সাতক্ষীরা',
  'Shariatpur': 'শরীয়তপুর',
  'Sherpur': 'শেরপুর',
  'Sirajganj': 'সিরাজগঞ্জ',
  'Sunamganj': 'সুনামগঞ্জ',
  'Sylhet': 'সিলেট',
  'Tangail': 'টাঙ্গাইল',
  'Thakurgaon': 'ঠাকুরগাঁও',
};
